name: CI Build UniMath

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    # Based on https://github.com/marketplace/actions/set-up-ocaml
    # Prime the caches every Monday
    - cron: 0 1 * * MON

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains two jobs, called "build-ubuntu" and "build-macos"

  sanity-checks:
    name: Sanity Checks
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install coq
          type coqc
          coqc --version
      - name: Run sanity checks
        run: |
          cd $GITHUB_WORKSPACE
          time make -k sanity-checks

  build-Unimath-ubuntu:
    name: Build UniMath (Ubuntu)
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: ocaml/setup-ocaml@v2 # to enable dune cache
        with:
          ocaml-compiler: ocaml-base-compiler.4.14.0
          dune-cache: true
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install coq
          type coqc
          coqc --version
      - name: Build UniMath
        run: opam exec -- dune build --display=short --cache=enabled


  build-coq-and-Unimath-ubuntu:
    name: Build Coq and UniMath (Ubuntu)
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install build-essential git ocaml ocaml-nox ocaml-native-compilers camlp5 libgtk2.0 liblablgtk-extras-ocaml-dev ocaml-findlib libnum-ocaml-dev emacs ocaml-dune libzarith-ocaml-dev
      - name: Build UniMath
        run: |
          cd $GITHUB_WORKSPACE
          time make -j2 TIMECMD=time BUILD_COQ=yes

  build-macos:
    name: Build UniMath (MacOS)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ocaml-base-compiler.4.14.0
          dune-cache: true
      - name: Install build dependencies
        run: opam install . --deps-only
      - name: Build UniMath
        run: opam exec -- dune build --display=short --cache=enabled

