name: CI-Build-UniMath

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains two jobs, called "build-ubuntu" and "build-macos"

  build-ubuntu:
    # Need a name for the job, see https://stackoverflow.com/questions/68554735/github-action-status-check-missing-from-the-list-of-checks-in-protected-branch-s
    name: Build-UniMath-and-Sanity-Checks
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      
      # Install everything needed for building UniMath (and more)
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install build-essential git ocaml ocaml-nox ocaml-native-compilers camlp5 libgtk2.0 libgtksourceview2.0 liblablgtk-extras-ocaml-dev ocaml-findlib libnum-ocaml-dev emacs

      # Change into UniMath directory and build Coq and UniMath
      - name: Build UniMath
        run: |
          cd $GITHUB_WORKSPACE
          time make BUILD_COQ=yes -j2 TIMECMD=time

      # Change into UniMath directory and run sanity checks
      - name: Change into UniMath directory and run sanity checks
        run: |
          cd $GITHUB_WORKSPACE
          time make TIMECMD=time sanity-checks

  build-macos:
    name: Build-UniMath-on-MacOS
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install build dependencies
        run: |
           brew config
           brew install coq
           type coqc
           coqc --version
      - name: Build UniMath
        run: |
          cd $GITHUB_WORKSPACE
          time make -j2 TIMECMD=time

