
name: CI Build Satellites

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    # Prime the caches every Monday
    - cron: 0 1 * * MON
  workflow_dispatch:

    # This builds all the satellites in parallel. They all build what they need
    # from UniMath and use dune cache to (hopefully) not having to rebuild more
    # than necessary.

    # The satellites currently breaks when using a modern version of Coq,
    # that's why we use the one in Ubuntu 20.04, which is 8.11.0.

jobs:
  build-satellite-typetheory:
    name: Build TypeTheory
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Install OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ocaml-base-compiler.4.14.0
          dune-cache: true
      - run: |
          sudo apt-get update
          sudo apt-get install coq
      - run: opam pin add dune 3.5.0
      - name: Clone TypeTheory
        run: |
          git clone https://github.com/m-lindgren/TypeTheory.git
          pushd TypeTheory
          git checkout dune-support
          popd
      - name: Compile TypeTheory
        run: opam exec -- dune build TypeTheory --display=short --cache=enabled

  build-satellite-sethits:
    name: Build SetHITs
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Install OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ocaml-base-compiler.4.14.0
          dune-cache: true
      - run: |
          sudo apt-get update
          sudo apt-get install coq
      - run: opam pin add dune 3.5.0
      - name: Clone SetHITs
        run: |
          git clone https://github.com/m-lindgren/SetHITs.git
          pushd SetHITs
          git checkout dune-support
          popd
      - name: Compile SetHITs
        run: opam exec -- dune build SetHITs --display=short --cache=enabled

  build-satellite-largecatmodules:
    name: Build Large Cat Modules
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Install OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ocaml-base-compiler.4.14.0
          dune-cache: true
      - run: |
          sudo apt-get update
          sudo apt-get install coq
      - run: opam pin add dune 3.5.0
      - name: Clone largecatmodules
        run: |
          git clone https://github.com/m-lindgren/largecatmodules.git
          pushd largecatmodules
          git checkout dune-support
          popd
      - name: Compile largecatmodules
        run: opam exec -- dune build largecatmodules --display=short --cache=enabled

  build-satellite-grpdhits:
    name: Build GrpdHITs
    runs-on: ubuntu-22.04 # This compiles fine with coq 8.15
    steps:
      - uses: actions/checkout@v3
      - name: Install OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ocaml-base-compiler.4.14.0
          dune-cache: true
      - run: |
          sudo apt-get update
          sudo apt-get install coq
      - run: opam pin add dune 3.5.0
      - name: Clone GrpdHITs
        run: |
          git clone https://github.com/m-lindgren/GrpdHITs.git
          pushd GrpdHITs
          git checkout dune-support
          popd
      - name: Compile GrpdHITs
        run: opam exec -- dune build GrpdHITs --display=short --cache=enabled
